name: shopify_pricesync_v2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  csv: ^6.0.0
  path_provider: ^2.0.15
  share_plus: ^11.1.0
  pdf: ^3.10.7
  intl: ^0.20.2
  printing: ^5.11.0
  open_filex: ^4.3.4
  shared_preferences: ^2.5.3
  sqflite: ^2.3.0
  hive_flutter: ^1.1.0
  permission_handler: ^12.0.1
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1

  firebase_core: ^3.3.0
  firebase_auth: ^5.3.1
  flutter_secure_storage: ^9.2.2
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.0
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/ijc_logo.png

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans.ttf

flutter_native_splash:
  color: "#FDF6EC"
  image: assets/ijc_logo.png
  android: true
  ios: true
  web: false

